import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import earthHero from '../../public/images/profile/earth-hero.png'
import data from '../../public/images/profile/data.png'
import leaf from '../../public/images/profile/leaf.svg'
import bottle from '../../public/images/profile/bottle.svg'
import glass from '../../public/images/profile/glass.svg'
import magnet from '../../public/images/profile/magnet.svg'
import world from '../../public/images/svgs/theWorld.svg'
import trashbin from '../../public/images/profile/trashbin.png'
import earth from '../../public/images/profile/earth.png'
import { FaArrowUp } from 'react-icons/fa';
import AnimatedText from '@/components/AnimatedText';
import { Primary } from '@/components/Button';
import React, { useEffect } from 'react';
import WasteSortingSteps from '@/components/WasteSortingSteps';

const Type = ({title, summary, link, image}) => {
  return (
      <div className='w-full flex flex-col items-start justify-between mr-2'>
        <div className='w-1/5'><Image src={image} alt="Icon" className='w-full h-auto'/></div>
          <Link 
            href={link}
            className='mt-2 flex space-x-1 w-full items-center justify-start text-dark hover:text-primary'
            >
                <h2 className='text-left text-xl font-bold'>{title}</h2>
                <FaArrowUp className="text-medium rotate-90" />
          </Link>
          <p className='my-2 font-regular text-dark/75 text-s'>{summary}</p>
      </div>
  )
}

export default function Home() {
  useEffect(() => {
    const hash = window.location.hash.substring(1);
  
    if (hash) {
      scrollToSection(hash);
    }
  }, []);

  const scrollToSection = (sectionId) => {
    const section = document.getElementById(sectionId);
  
    if (section) {
      section.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <>
      <Head>
        <title>Pilah Sampah | Rumah</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=' items-center text-dark w-full min-h-screen'>
        {/* Hero Section */}
        <Layout className='pt-12'>
          <div className="flex items-center justify-between w-full">
            <div className='w-2/5'>
            <Image src={earthHero} alt="Photo Profile" className='w-full h-auto'/>
            </div>
            <div className='w-1/2 flex flex-col item-center self-center'>
              <p className='text-primary text-2xl font-medium'>- EcoSort -</p>
              <AnimatedText text="Sampah Terpilah, Alam Terjaga." className='!text-6xl !text-left'/>
              <p className='my-4 text-base font-medium'>
              Temukan cara mudah untuk memilah sampah, mendaur ulang, dan menjaga lingkungan demi masa depan yang lebih baik.
              </p>
              <Primary
                link="#misi-section"
                title="Jelajahi"
                onClick={() => scrollToSection('misi-section')}
              />
            </div>
          </div>
        </Layout>
        {/* End of Hero Section */}

        {/* Category Section */}
        <div id="misi-section" >
        <Layout className='!bg-lightgrey !py-24'>
            <AnimatedText text='Tipe Sampah' className='!text-4xl pb-8 col-span-12'/>
            <div className='grid grid-cols-12 gap-12'>
                <div className='col-span-3'>
                    <Type 
                        image={leaf}
                        title="Organik"
                        summary="Sampah yang berasal dari bahan alami dan bisa terurai secara alami (biodegradable)."
                        link="/sampah-organik"
                    />
                </div>
                <div className='col-span-3'>
                    <Type 
                        image={bottle}
                        title="Plastik"
                        summary="Sampah yang terbuat dari bahan sintetis atau polimer."
                        link="/sampah-plastik"
                    />
                </div>
                <div className='col-span-3'>
                    <Type 
                        image={glass}
                        title="Kaca"
                        summary="Sampah berbahan dasar kaca yang sulit terurai di alam."
                        link="/sampah-kaca"
                    />
                </div>
                <div className='col-span-3'>
                    <Type 
                        image={magnet}
                        title="Logam"
                        summary="Sampah berbahan dasar logam yang dapat didaur ulang berkali-kali."
                        link="/sampah-logam"
                    />
                </div>
            </div>
        </Layout>
        </div>
        {/* End of Category Section */}

        {/* Fact Section */}
        <Layout className='!py-32'>
            <div className="grid w-full grid-cols-12 gap-16 items-center">
              <div className='col-span-7 flex flex-col items-start justify-start'>
                <div>
                  <AnimatedText text="Taukah Kamu?" className='!text-4xl !text-left'/>
                  <p className='my-4 text-base font-medium'>
                  Setiap hari, kita menghasilkan ribuan ton sampah yang berdampak langsung pada lingkungan. Namun, dengan memilah dan mendaur ulang, kita bisa mengurangi jejak ekologis dan melindungi Bumi kita.
                  </p>
                </div>
                <div className="grid w-full grid-cols-3 gap-16">
                  <div className='col-span-1 items-start justify-center'>
                    <AnimatedText text="300 jt" className='!text-3xl !text-left'/>
                    <h2 className='text-sm font-medium text-dark/75'> ton plastik diproduksi setiap tahun</h2>
                  </div>
                  <div className='col-span-1 items-start justify-center'>
                    <AnimatedText text="9%" className='!text-3xl !text-left'/>
                    <h2 className='text-sm font-medium text-dark/75'>dari plastik global yang didaur ulang</h2>
                  </div>
                  <div className='col-span-1 items-start justify-center'>
                    <AnimatedText text="95%" className='!text-3xl !text-left'/>
                    <h2 className='text-sm font-medium text-dark/75'>energi dapat dihemat dengan mendaur ulang aluminium</h2>
                  </div>
                </div>
            </div>
              <div className='col-span-5 flex flex-col items-end justify-end'>
                <Image src={data} alt="Photo Profile" className='w-full h-auto'/>
              </div>
            </div>
            </Layout>
            {/* End of Fact Section */}

            {/* The Way Section */}
            <Layout className='!pt-0 !pb-24'>
                <div className="grid w-full grid-cols-12 gap-16 items-center">
                  <div className='col-span-5 flex flex-col items-end justify-end'>
                    <Image src={trashbin} alt="Photo Profile" className='w-full h-auto'/>
                  </div>
                  <div className='col-span-7 flex flex-col items-start justify-start'>
                    <div>
                      <AnimatedText text="Apa yang bisa kamu lakukan?" className='!text-4xl !text-left !mb-4'/>
                    </div>
                    <WasteSortingSteps/>
                  </div>
                </div>
                </Layout>
                {/* End of the Way Section */}

            {/* Quotes Section */}
            <Layout className='!py-12 !pb-24'>
            <div className="grid w-full grid-cols-12 gap-16 items-center">
              <div className='col-span-12 flex items-center justify-center'>
                <Image src={earth} alt="earth" className='w-1/2'/>
              </div>
              <p className='col-span-12 text-4xl font-medium text-center'>
              &quot;Alam tidak butuh kata-kata mutiara.<br/>Alam butuh aksi nyata.&quot;
              </p>
            </div>
            </Layout>

      </main>
    </>
  )
}
